### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by drf5n** [adafruit/Adafruit_Sensor#10]
Do you install this file the same as the drivers?  

    cd ..../Arduino/libraries
    git clone git@github.com:adafruit/Adafruit_Sensor.git
    # Restart Arduino

**Comment by microbuilder** [comment]
You should install this through the Arduino Library Manager: https://learn.adafruit.com/adafruit-arduino-ide-setup/arduino-1-dot-6-x-ide
