### ISSUE TITLE
make: don't know how to make Adafruit_Sensor.o

### ISSUE THREAD

**Issue by rhinos** [adafruit/Adafruit_Sensor#13]
Hello,

I'm trying to play with samples scripts and meet troubles while compilation.
My env : OS: OpenBSD 6.1 with arduino package.
My Board is a Arduino MEGA 2560.
The sample script is the one available with Adafruit_FXAS21002C driver.
The make stop with this message : 
make: don't know how to make Adafruit_Sensor.o (prerequisite of: applet/core.a) 

I  tried other libs like Servo without issues.

Note : I'm note using Arduino IDE (not available)

Thank's for your help

Bruno.

**Comment by ladyada** [comment]
are you using Arduino IDE?

**Comment by rhinos** [comment]
Hello,

No, Arduino IDE is not available on my system.

**Comment by ladyada** [comment]
you'll have to adjust your makefile, the Sensor interface is provided as a header file only, there is no associated C code :)

**Comment by rhinos** [comment]
Hello,

Thank's for your reply. But could you be more explicit ? I'am new to C/C++ world and Makefile (python programer). You mean that i have to had something like that in my Makefile ?
CFLAGS=-I/directory/to/add

In my Makefile there is this. 
# If your sketch uses any libraries, list them here, eg.
# LIBRARIES=EEPROM LiquidCrystal Wire
#
# If you want to use the Ethernet library, use:
# LIBRARIES=SPI Ethernet IPAddress Dhcp Dns EthernetClient EthernetServer \
#               EthernetUdp utility/w5100 utility/socket new
#
# To use the SD library:
# LIBRARIES=SD File utility/SdFile utility/SdVolume utility/Sd2Card
LIBRARIES=Wire Adafruit_FXAS21002C Adafuit_Sensor
############################################################################
# Below here nothing should be changed...

I try a lot of differents settings/syntax but steel the same.

Thanks.

**Comment by rhinos** [comment]
hello,

I add -Ilibrairies/Adafruit_Sensor and it's solved the sensor error.

Thanks.
