### ISSUE TITLE
Ver 6.3.3 Sensor ASAIR 2302

### ISSUE THREAD

**Issue by James11325** [adafruit/Adafruit_Sensor#23]
Three months ago I am operating 5 mushroom growing houses without any problem. Each room has 5 ASAIR 2302 sensors. Everything worked fine on a Raspberry PI3 B +
Two days ago I switched to version 6.3.3 and the sensors no longer work.
What should I do?
Thank you

**Comment by ladyada** [comment]
hiya this library isnt for ASAIR 2302 sensors, or raspberry pi :)
