### ISSUE TITLE
Provide distinction in terms of BNO055

### ISSUE THREAD

**Issue by shantanoo-desai** [adafruit/Adafruit_Sensor#24]
Hi I just spent half a day pondering upon the fact that BNO055 can be used along with this library only to obtain orientation and not the accelerometer values.

I was aiming to use the event method to use `event.orientation` for Roll, Pitch, Yaw and `event.acceleration` to obtain linear accerleration in X, Y, Z directions but if I use the code I get the same values for `event.acceleration` and `event.orientation`

[SE Query supporting this Issue created by Me](https://arduino.stackexchange.com/questions/56937/get-accelerometer-values-from-bno055-using-adafruits-unified-sensor-library)

Looking for some discussion on the same.

**Comment by shantanoo-desai** [comment]
@ladyada no I mean using `Adafruit_Sensor` library for BNO055 to get both orientation and linear acceleration. Something like the following, since the README mentions BNO055 and this sensor can provide all the linear acceleration and orientation.

Maybe in the `README` it might be worth mentioning that using `event.acceleration` with BNO055 wont provide acceleration values
```
sensors_event_t event;
  bno.getEvent(&event);

  Serial.print(F("Orientation: "));
  Serial.print((float)event.orientation.heading);
  Serial.print(F(" "));
  Serial.print((float)event.orientation.pitch);
  Serial.print(F(" "));
  Serial.print((float)event.orientation.roll);
  Serial.println(F(""));
 Serial.print((float)event.acceleration.x);
 Serial.println(F(""));
 Serial.print((float)event.acceleration.y);
 Serial.println(F(""));
 Serial.print((float)event.acceleration.z);
 Serial.println(F(""));
```

**Comment by ladyada** [comment]
yep please open this issue in the BNO055 library :)
