### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by shalinee1234** [adafruit/Adafruit_Sensor#25]
Arduino: 1.8.7 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Enabled, 4M (no SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

In file included from C:\Users\shalinee mishra\Documents\Arduino\libraries\Adafruit_IO_Arduino\src/wifi/AdafruitIO_ESP8266.h:18:0,

                 from C:\Users\shalinee mishra\Documents\Arduino\libraries\Adafruit_IO_Arduino\src/AdafruitIO_WiFi.h:32,

                 from C:\Users\SHALIN~1\AppData\Local\Temp\arduino_modified_sketch_178491\adafruitio_15_temp_humidity.ino:26:

C:\Users\shalinee mishra\Documents\Arduino\libraries\Adafruit_IO_Arduino\src/AdafruitIO.h:23:31: fatal error: ArduinoHttpClient.h: No such file or directory

 #include "ArduinoHttpClient.h"

                               ^

compilation terminated.

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by ladyada** [comment]
yes this is known! the current issue for getting it fixed by releasing a new version of httpclient is here
https://github.com/arduino-libraries/ArduinoHttpClient/issues/51
