### ISSUE TITLE
Issue with Unified sensor library or Adafruit BNO055

### ISSUE THREAD

**Issue by amichelmore** [adafruit/Adafruit_Sensor#34]
Hi,

The Adafruit BNO055 seems to have some issues with the Adafruit unified sensor library. The sensors_event_t returned seems to contain incorrect components. The acceleration, and gyro components both return the orientation data. Here is a stack exchange question that details this more. 
https://arduino.stackexchange.com/questions/56937/get-accelerometer-values-from-bno055-using-adafruits-unified-sensor-library?newreg=c6a3bcfaa15e48438c38521da1a330b5  

I'm not exactly sure where to put this information but I'll leave it here as well as some other places. 

Here is the code that yields this problem:
#include <math.h>

#include <Wire.h>
#include <Adafruit_Sensor.h>
#include <Adafruit_BNO055.h>
#include <utility/imumaths.h>

  
Adafruit_BNO055 bno = Adafruit_BNO055(55);

void setup(void) 
{
  Serial.begin(9600);
  Serial.println("Orientation Sensor Test"); Serial.println("");
  
  /* Initialise the sensor */
  
  if(!bno.begin())
  {
    /* There was a problem detecting the BNO055 ... check your connections */
    Serial.print("Ooops, no BNO055 detected ... Check your wiring or I2C ADDR!");
    while(1);
  }
  
  delay(1000);
    
  bno.setExtCrystalUse(true);
}

void loop(void) 
{
  /* Get a new sensor event */ 
  sensors_event_t event; 
  bno.getEvent(&event);
  
  /* Display the floating point data */
  Serial.print("RPY X: ");
  Serial.print(event.orientation.x, 4);
  Serial.print("\tY: ");
  Serial.print(event.orientation.y, 4);
  Serial.print("\tZ: ");
  Serial.print(event.orientation.z, 4);
  Serial.println("");

  Serial.print("Gyro X: ");
  Serial.print(event.gyro.x, 4);
  Serial.print("\tY: ");
  Serial.print(event.gyro.y, 4);
  Serial.print("\tZ: ");
  Serial.print(event.gyro.z, 4);
  Serial.println("");

  Serial.print("Acceleration X: ");
  Serial.print(event.acceleration.x, 4);
  Serial.print("\tY: ");
  Serial.print(event.acceleration.y, 4);
  Serial.print("\tZ: ");
  Serial.print(event.acceleration.z, 4);
  Serial.println("");
  
  delay(100);
}

Thanks for your time!

**Comment by ladyada** [comment]
these event types overlap in the event structure, you cannot get multiple event data out at once

use this for getting sensor-api data
https://github.com/adafruit/Adafruit_BNO055/blob/master/examples/sensorapi/sensorapi.ino
and this for multiple
https://github.com/adafruit/Adafruit_BNO055/blob/master/examples/read_all_data/read_all_data.ino

**Comment by amichelmore** [comment]
Oh I see thank you for the help!
