### ISSUE TITLE
Resolution or Accuracy

### ISSUE THREAD

**Issue by rob040** [adafruit/Adafruit_Sensor#35]
There is a mixup of using sensor **Resolution vs. Accuracy**.

The AHT10 sensor reports the following:

```
Adafruit AHT10 test!
AHT10 Found!
------------------------------------
Sensor:       AHT10_T
Type:         Ambient Temp (C)
Driver Ver:   1
Unique ID:    257
Min Value:    -40.00
Max Value:    85.00
Resolution:   0.30
------------------------------------

------------------------------------
Sensor:       AHT10_H
Type:         Relative Humidity (%)
Driver Ver:   1
Unique ID:    256
Min Value:    0.00
Max Value:    100.00
Resolution:   2.00
------------------------------------
```

The AHT10 temperature resolution is 0.01C but its overall accuracy is +/- 0.30 C.
The same goes for RH.

What is expected of sensor to enter as "resolution" parameter?
I gather that is not made clear, and causes this mixup.

(i'll enter also ticket in AHT1x library about this; these Adafruit libraries should agree on how to use this)

**Comment by ladyada** [comment]
closing duplicate, answered in other post :)
