### ISSUE TITLE
Adafruit_ADXL343.h: No such file or directory

### ISSUE THREAD

**Issue by FlaminHat** [adafruit/Adafruit_Sensor#36]
Arduino: 1.8.9 (Mac OS X), Board: "Arduino Ethernet"

Multiple libraries were found for "Adafruit_Sensor.h"
 Used: /Users/imac/Documents/Arduino/libraries/Adafruit_Sensor
 Not used: /Users/imac/Documents/Arduino/libraries/Adafruit_Unified_Sensor
sensortest:3:30: error: Adafruit_ADXL343.h: No such file or directory
compilation terminated.
exit status 1
Adafruit_ADXL343.h: No such file or directory

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by caternuson** [comment]
Did you install the ADXL345 library?
https://learn.adafruit.com/adxl343-breakout-learning-guide/arduino#installation-3018247-6

**Comment by FlaminHat** [comment]
Arduino: 1.8.9 (Mac OS X), Board: "Arduino Ethernet"

In file included from /Users/imac/Documents/Arduino/libraries/Adafruit_ADXL343/examples/sensortest/sensortest.ino:3:0:
/Users/imac/Documents/Arduino/libraries/Adafruit_ADXL343/Adafruit_ADXL343.h:27:37: fatal error: Adafruit_BusIO_Register.h: No such file or directory
compilation terminated.
exit status 1
Error compiling for board Arduino Ethernet.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by caternuson** [comment]
Install it via Library Manager so dependencies are taken care of:
https://github.com/adafruit/Adafruit_ADXL343/blob/bf29bba97ef1a984201036a8e1eba4976b1df34e/library.properties#L10
You may also need to update your Arduino IDE. The library dependency feature was added at 1.8.10:
https://github.com/arduino/Arduino/releases/tag/1.8.10

**Comment by FlaminHat** [comment]
Installed via Library Manager, and I have now updated my IDE.

Getting this now:

Arduino: 1.8.15 (Mac OS X), Board: "Arduino Ethernet"

In file included from /Users/imac/Documents/Arduino/libraries/Adafruit_ADXL343/examples/sensortest/sensortest.ino:3:0:
/Users/imac/Documents/Arduino/libraries/Adafruit_ADXL343/Adafruit_ADXL343.h:27:10: fatal error: Adafruit_BusIO_Register.h: No such file or directory
 #include <Adafruit_BusIO_Register.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Arduino Ethernet.


This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by caternuson** [comment]
Same error. Since you previously tried to install it with the older version, simply updating may not be dealing with dependencies correctly. It may be assuming they are already taken care of. Try installing the BusIO library via Library Manager:
https://github.com/adafruit/Adafruit_BusIO

**Comment by FlaminHat** [comment]
Tried that, now giving me this:

Arduino: 1.8.15 (Mac OS X), Board: "Arduino Ethernet"

/Users/imac/Documents/Arduino/libraries/Adafruit_ADXL343/examples/sensortest/sensortest.ino: In function 'void setup()':
sensortest:128:9: error: 'class Adafruit_ADXL343' has no member named 'printSensorDetails'
   accel.printSensorDetails();
         ^~~~~~~~~~~~~~~~~~
exit status 1
'class Adafruit_ADXL343' has no member named 'printSensorDetails'


This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by caternuson** [comment]
Unknown. Something just seems mixed up with your library installs. That method gets inherited from the sensor lib:
https://github.com/adafruit/Adafruit_Sensor/blob/6cea0d9c554930e3914d6629235ff0a044f452ab/Adafruit_Sensor.h#L182
