### ISSUE TITLE
sensor_t typename clash

### ISSUE THREAD

**Issue by maxgerhardt** [adafruit/Adafruit_Sensor#37]
https://github.com/adafruit/Adafruit_Sensor/blob/69d2d4f128458c7f7e6d56b583a8261ea234971b/Adafruit_Sensor.h#L144-L155

with its very generic `sensor_t` typename directly clashes with

https://github.com/espressif/arduino-esp32/blob/5f6d093d4a8a371c78acd6e1a0e7a95b7346cbec/tools/sdk/esp32/include/esp32-camera/driver/include/esp_camera.h#L193

A type used in the `esp_camera` system, aka a camera sensor. Using both these libraries in the same code file is not possible (but in split files it is).

Not sure if that should be fixed since changing the name breaks compatibility, but at least FYI for other people running into this error during development, as they [did in our forum](https://community.platformio.org/t/pio-libdeps-esp32cam-adafruit-unified-sensor-adafruit-sensor-h3-error-conflicting-declaration-typedef-struct-sensor-t-sensor-t/27366).

**Comment by udif** [comment]
Can't you avoid this in your code by encapsulating one of them in a  namespace?

**Comment by maxgerhardt** [comment]
Could possibly be running into https://softwareengineering.stackexchange.com/questions/298576/c-extensible-namespaces-how-to-force-declarations-back-into-global-namespace, but have not tried it.

**Comment by y3nd** [comment]
https://softwareengineering.stackexchange.com/a/298579
