### ISSUE TITLE
Add support for particles...

### ISSUE THREAD

**Issue by tyeth** [adafruit/Adafruit_Sensor#40]
There is a [PM2.5 sensor as part of wippersnapper](https://github.com/adafruit/Wippersnapper_Components/blob/main/components/i2c/pmsa003i/definition.json), and wippersnapper have [listed](https://github.com/adafruit/Wippersnapper_Components#i2c-sensor-types) the following relevant supported sensor types (although the _env variants seem unimplemented):
"pm10-std"
"pm25-std"
"pm100-std"
"pm10-env"
"pm25-env"
"pm100-env"

I plan to add the [Sensirion SEN55](https://github.com/adafruit/Wippersnapper_Components/issues/103), which has particle sensing at 0.5, 1, 2.5, 4, and 10 (micron?) in particles per cm3, and for all except <0.5um there are readings in ug/m3 (SI unit?), along with Temp(c)/Humidity(%RH), a Voc index and Nox index both without units. I assume the nox and voc are irrelevant as the device doesn't offer units but an "index".

The wippersnapper adding a sensor guide says to file an issue here for unsupported sensor types.
https://learn.adafruit.com/how-to-add-a-new-component-to-adafruit-io-wippersnapper/adding-an-i2c-component-driver#:~:text=NOTE%20%2D%20If%20you%27re%20adding%20a%20sensor%20that%20does%20not%20yet%20have%20a%20predefined%20sensor_type%2C%20please%20add%20a%20new%20issue%20to%20Adafruit_Sensor.

I guess I'm filing an issue to get support for count(#)/cm3 as that seems to be the preferred SI unit. I do commonly see a converted ug/m3 so anyone's input here would be good.  I'd love support for the pm05 pm10 pm25 pm40 and pm100 too.

**Comment by brentru** [comment]
`count(#)/cm3 ` works, is there a shorthand term (how the library would refer to this) for this measurement type?

**Comment by brentru** [comment]
I'm also game for supporting the PM sizes too

**Comment by tyeth** [comment]
> `count(#)/cm3 ` works, is there a shorthand term (how the library would refer to this) for this measurement type?

In the header file their calling it #/cm3

**Comment by brentru** [comment]
@tyeth  Do we still need this measurement type?
