### ISSUE TITLE
Add requested support for NOx/VOC index

### ISSUE THREAD

**Issue by tyeth** [adafruit/Adafruit_Sensor#42]
This is a ticket for the pull request for NOX/VOC index.
[What is Sensirion’s NOx Index?](https://sensirion.com/media/documents/9F289B95/6294DFFC/Info_Note_NOx_Index.pdf)
[What is Sensirion’s VOC Index?](https://sensirion.com/media/documents/02232963/6294E043/Info_Note_VOC_Index.pdf)

Meant to support the [Sensirion SEN55/SEN54](https://sensirion.com/products/catalog/SEN55/), but may also be useful for the [BME680](https://cdn-shop.adafruit.com/product-files/3660/BME680.pdf)

**Comment by tyeth** [comment]
@brentru as requested. This is for #41 etc.

**Comment by brentru** [comment]
Resolved in https://github.com/adafruit/Adafruit_Sensor/pull/41
