### ISSUE TITLE
avr\pgmspace.h  Compilation Error

### ISSUE THREAD

**Issue by rogerguess** [adafruit/Adafruit_Sensor#5]
I am unable to compile, as it is looking for that file. Does it expect the file to be in the library, or as part of a base path?

I am using the esptool programmer, and targeting the generic esp8266 board.

**Comment by ladyada** [comment]
Thats a specific AVR header file, we haven't tested this library with ESP8266, please contact the seller of the ESP8266 board for support, perhaps they can help you. Thanks! :)

**Comment by rogerguess** [comment]
...ok. I am using your new HUZZAH ESP8266 Breakout. Might be a few of us that would want to know how to do this without having to become experts on the 8266.

https://www.adafruit.com/products/2471

**Comment by ladyada** [comment]
Yep AVR == Arduino chipset
ESP8266 support is only a few days old, eventually all the libraries may be ported, but it will take a while :)
